version: "2"
services:
  nginx:
    build: ./nginx/
    ports:
        - 8888:80
    links:
        - php
    volumes_from:
        - app

  php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app

  app:
    build: ./php/
    volumes:
        - .:/var/www/html
    command: "true"

  mysql:
    build: ./mysql/
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: project
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project

  data:
    build: ./mysql/
    volumes:
        - /var/lib/mysql
    command: "true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql:db
    environment:
      MYSQL_USER: project
      MYSQL_ROOT_PASSWORD: project
